name: ðŸ› Bug report
description: Provide information about a problem
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Description
      description: Provide a short description of the problem. What's expected and what actually happens, etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        Provide environment information.
        - You can grab **Application version** from `Help -> About EFI Boot Editor`
        - Exact **Operating system** version/distribution much appreciated
        - Please provide information about your UEFI environment like `Motherboard: MSI PRO X670`, `BIOS version: XX 01/01/1970`, etc.
      value: |
        - Application version:
        - Operating system:
        - EFI/BIOS/Motherboard vendor:
        - EFI/BIOS version:
    validations:
      required: true
  - type: textarea
    attributes:
      label: Raw EFI data
      description: |
        Please provide raw EFI data if possible, you can generate it from `Help -> Dump raw EFI data`

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional information
      description: |
        Whenever possible please also provide any additional information that might help troubleshoot the issue.
        Like:
         - Boot menu screenshot for comparison with EFI Boot Manager output
         - on Linux: `efibootmgr` output
         - on Windows: `bcdedit /enum firmware` output
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: If applicable, provide list of exact steps to reproduce the problem.
      placeholder: |
        1. Click '...' in the GUI
        2. See error...
    validations:
      required: false
