if (CPACK_GENERATOR STREQUAL "DEB")
    list(REMOVE_ITEM CPACK_COMPONENTS_ALL "Runtime")
endif()

if (NOT CPACK_GENERATOR STREQUAL "AppImage")
    list(REMOVE_ITEM CPACK_COMPONENTS_ALL "AppImage")
endif()
