name: Build EFIBootEditor

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      compiler:
        required: true
        type: string
      build-config:
        required: true
        type: string
      version:
        required: true
        type: string

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  INPUT_COMPILER: ${{ inputs.compiler }}

jobs:
  build:
    name: ${{ inputs.os }} Qt ${{ matrix.qt-version }} with ${{ inputs.compiler }}
    runs-on: ${{ inputs.os }}
    strategy:
      fail-fast: false
      matrix:
        qt-version:
          - 5.15.2 # Supported in Ubuntu Resolute Raccoon until 2031-05-31
          - 6.2.4  # Supported in Ubuntu Jammy Jellyfish until 2027-04-01
          - 6.11.0 # Supported until 2026-09-22
        exclude:
          - qt-version: ${{ endsWith(inputs.os, 'arm') && '5.15.2' || 'none' }}
          - qt-version: ${{ endsWith(inputs.os, 'arm') && '6.2.4' || 'none' }}
          - qt-version: ${{ inputs.os == 'macos-26' && '6.2.4' || 'none' }}
          - qt-version: ${{ inputs.os == 'macos-26' && '6.8.3' || 'none' }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@33522472633dbd32578e909b315f5ee43ba878ce
        with:
          key: ${{ inputs.os }}-${{ inputs.compiler }}-${{ inputs.build-config }}-${{ matrix.qt-version }}
          restore-keys: |
            ${{ inputs.os }}-${{ inputs.compiler }}-${{ inputs.build-config }}
            ${{ inputs.os }}-${{ inputs.compiler }}
            ${{ inputs.os }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@95e58e9a2cdfd71adc6e0353d5c52f41a045d225
        with:
          languages: cpp
          queries: security-and-quality
        if: inputs.build-config == 'Debug'
        continue-on-error: true

      - name: Set up Qt environment
        uses: jurplel/install-qt-action@48d3ad6db93f3627c8ee7a0454bc6f3744f7e730
        with:
          cache: true
          version: ${{ matrix.qt-version }}
          # https://github.com/miurahr/aqtinstall/pull/1000
          aqtsource: git+https://github.com/miurahr/aqtinstall.git@8c3695d4a4e1ceabf6a74dc6c79681656dc6b74b

      - name: Install CMake
        run: |
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
          sudo apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"
          sudo apt-get update
          sudo apt-get install cmake
          mv /usr/local/bin/cmake /usr/local/bin/cmake3
          mv /usr/local/bin/cpack /usr/local/bin/cpack3

          cmake --version
        shell: bash
        if: startsWith(inputs.os, 'ubuntu')

      - name: Install libfuse2
        run: sudo apt-get install libfuse2
        shell: bash
        if: startsWith(inputs.os, 'ubuntu')

      - name: Install linuxdeploy
        run: |
          DIR=$(mktemp -d)
          echo "${DIR}" >> ${GITHUB_PATH}
          ARCH=${{ endsWith(inputs.os, 'arm') && 'aarch64' || 'x86_64' }}
          wget -c -nv https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-${ARCH}.AppImage -O ${DIR}/linuxdeploy
          wget -c -nv https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-${ARCH}.AppImage -O ${DIR}/linuxdeploy-plugin-qt
          wget -c -nv https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-${{ endsWith(inputs.os, 'arm') && 'aarch64' || 'x86_64' }}.AppImage -O ${DIR}/appimagetool
          chmod +x ${DIR}/*
        shell: bash
        if: startsWith(inputs.os, 'ubuntu')

      - name: Install efivar
        run: sudo apt-get install libefiboot1 libefiboot-dev libefivar-dev
        shell: bash
        if: startsWith(inputs.os, 'ubuntu')

      - name: Install libxkbcommon-x11-0 and libxcb-cursor0 and zlib1g-dev
        run: sudo apt-get install libxkbcommon-x11-0 libxcb-cursor0 zlib1g-dev
        shell: bash
        if: startsWith(inputs.os, 'ubuntu')

      - name: Install xvfb imagemagick
        run: sudo apt-get install xvfb imagemagick
        shell: bash
        if: startsWith(inputs.os, 'ubuntu')

      - name: Install imagemagick
        run: arch -arm64 brew install imagemagick
        shell: bash
        if: startsWith(inputs.os, 'macos')

      - name: Install imagemagick
        run: winget install --accept-source-agreements ImageMagick.ImageMagick
        shell: bash
        if: startsWith(inputs.os, 'windows-2025')

      - name: Install zlib
        run: vcpkg install zlib
        shell: bash
        if: startsWith(inputs.os, 'windows')

      - name: Configure with ${{ inputs.compiler }}
        run: |
          cmake --preset ${{ inputs.build-config }} -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER=${{ inputs.compiler == 'Clang' && 'clang' || 'gcc' }} -DCMAKE_CXX_COMPILER=${{ inputs.compiler == 'Clang' && 'clang++' || 'g++' }} ${{ startsWith(inputs.os, 'macos') && startsWith(matrix.qt-version, '5') && '-DCMAKE_OSX_ARCHITECTURES="x86_64"' || '' }}
        shell: bash
        env:
          BUILD_VERSION: ${{ inputs.version }}
          BUILD_OS: ${{ inputs.os }}
        if: ${{ !startsWith(inputs.os, 'windows') }}

      - name: Build
        run: cmake --build --preset ${{ inputs.build-config }}
        shell: bash
        if: ${{ !startsWith(inputs.os, 'windows') }}

      - name: Configure and build with ${{ inputs.compiler }}
        run: |
          call "%programfiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ endsWith(inputs.os, 'arm') && 'arm64' || 'x64' }} || exit /b
          cmake --preset ${{ inputs.build-config }} -DCMAKE_TOOLCHAIN_FILE=%VCPKG_INSTALLATION_ROOT%\scripts\buildsystems\vcpkg.cmake -DCMAKE_VERBOSE_MAKEFILE=ON ${{ inputs.compiler == 'Clang' && '-DCMAKE_C_COMPILER=clang-cl.exe -DCMAKE_CXX_COMPILER=clang-cl.exe' || '' }} -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache || exit /b
          cmake --build --preset ${{ inputs.build-config }}
        shell: cmd
        env:
          BUILD_VERSION: ${{ inputs.version }}
          BUILD_OS: ${{ inputs.os }}
        if: startsWith(inputs.os, 'windows')

      - name: Run tests
        env:
          TEST_ALLOW_NO_EFI_ENTRIES: ${{ startsWith(inputs.os, 'macos') && 'true' || '' }}
        run: ${{ startsWith(inputs.os, 'ubuntu') && 'xvfb-run -a' || '' }} ctest --preset ${{ inputs.build-config }} -VV
        shell: bash

      - name: Check visuals
        id: visual
        continue-on-error: true
        run: ${{ startsWith(inputs.os, 'windows') && 'magick' || '' }} compare -metric RMSE -fuzz 2% build/${{ inputs.build-config }}/tests/screenshot.png tests/screenshots/${{ inputs.os }}.png diff.png
        shell: bash

      - name: Upload visual diff
        if: steps.visual.outcome == 'failure'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: visual-diff-${{ inputs.os }}-qt-${{ matrix.qt-version }}-${{ inputs.compiler }}
          path: |
            build/${{ inputs.build-config }}/tests/screenshot.png
            diff.png
          retention-days: 5

      - name: Package
        run: |
          for t in $(seq 1 20); do # FIXME: macOS has random hdiutil errors because of some protection mechanisms, just retry few times https://github.com/actions/runner-images/issues/7522#issuecomment-1556766641
            cmake --build --preset ${{ inputs.build-config }} --target package && exit 0
            rm -rf build/${{ inputs.build-config }}/dist/
          done
          exit 255
        shell: bash

      - name: Generate SBOM
        uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610
        with:
          output-file: build/${{ inputs.build-config }}/dist/EFIBootEditor-${{ github.sha }}-${{ inputs.os }}-qt-${{ matrix.qt-version }}.spdx
          upload-artifact: false
          upload-release-assets: false

      - name: Attest artifacts
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32
        with:
          subject-path: build/${{ inputs.build-config }}/dist/EFIBootEditor-*

      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: EFIBootEditor-${{ github.sha }}-${{ inputs.os }}-qt-${{ matrix.qt-version }}-${{ inputs.compiler }}
          if-no-files-found: error
          path: build/${{ inputs.build-config }}/dist/EFIBootEditor-*

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@95e58e9a2cdfd71adc6e0353d5c52f41a045d225
        if: inputs.build-config == 'Debug'
        continue-on-error: true
