name: Codacy Code Analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  codacy-analysis:
    name: Codacy Code Analysis
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Run Codacy Code Analysis
        uses: codacy/codacy-analysis-cli-action@4.0.2
        with:
          output: codacy.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647

      - name: Upload Codacy Code Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: codacy.sarif
