name: Draft release

on:
  push:
    branches: [master]

jobs:
  update_release_draft:
    runs-on: ubuntu-slim
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: release-drafter/release-drafter@34d80673e067bdc0c24568d3af899c216adcfaa9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
