name: Draft release

on:
  push:
    branches: [master]

jobs:
  update_release_draft:
    runs-on: ubuntu-slim
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: release-drafter/release-drafter@693d20e7c1ce1a81d3a41962f85914253b518449
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
