name: Draft release

on:
  push:
    branches: [master]

jobs:
  update_release_draft:
    runs-on: ubuntu-slim
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: release-drafter/release-drafter@c2e2804cc59f45f57076a99af580d0fedb697927
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
