name: Clang format

on: [push]

jobs:
  clang-format:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: cpp-linter/cpp-linter-action@4f2a4033eda6119c3bf1a4d30857a4c61c11c247
        id: linter
        with:
          version: 22
          style: file
      - name: Fail fast
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
