name: Clang format

on: [push]

jobs:
  clang-format:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: cpp-linter/cpp-linter-action@89288efe7a9b377406dcea651d756aa1ade3e4a3
        id: linter
        with:
          version: 21
          style: file
      - name: Fail fast
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
